# Site
repository: ylliang96/digital-resume
favicon: images/logo4.ico

# Personal info
name: Elaine Y. Liang
title: Digital Resume
email: yilienliang@gmail.com
location: College Station, TX
#website: Your website (eg. https://google.com)(optional)

# Dark Mode (true/false/never)
darkmode: false

# Social links
github_username:  ylliang96
linkedin_username: ylliang96
#orcid_username: 0000-0000-0000-0000

# Additional icon links
#additional_links:
#- title: Link name
#  icon: Font Awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#  url: Link url (eg. https://google.com)
# - title: another link
#   icon: font awesome brand icon name (eg. fa-twitter) (https://fontawesome.com/icons?d=gallery&s=brands&m=free)
#   url: Link url (eg. https://google.com)

# Google Analytics and Tag Manager
# Using more than one of these may cause issues with reporting
# gtm: "GTM-0000000"
# gtag: "UA-00000000-0"
# google_analytics: "UA-00000000-0"

# About Section
# about_title: About Me (Use this to override about section title)
about_profile_image: images/github_profile_pic.png
about_content: | # this will include new lines to allow paragraphs
  Elaine Y. Liang is currently pursuing her masterâ€™s degree in Industrial Engineering at Texas A&M University (College Station, TX). She often thinks the world is a gigantic machine, which consists of multiple subsystems and is always curious about how humans interact within. Besides spending her time mind-wandering, she also enjoys playing the cello, brewing coffee, and walking.

# Projects Section
# projects_title: Projects #(Use this to override about projects section title)

# Experience Section
# experience_title: Experience #(Use this to override about experience section title)

# Education Section
# education_title: Education #(Use this to override about education section title)

# More Section
# more_title: A Little More About Me #(Use this to override about more section title)
more_content: | # this will include new lines to allow paragraphs
  My skills include:
  <mark>R</mark>
  <mark>SQL</mark>
  <mark>Python</mark>
  <mark>MATLABL</mark>
  <mark>Data visualization</mark>
  <mark>Statistical Analysis</mark>

  I have also appread in ***Taiwanese Student Association at Texas A&M*** & ***2018 The Chinese University of Hong Kong International Student Summit***

# Footer
footer_show_references: false

# Build settings
# theme: modern-resume-theme (Use this is you are hosting your resume yourself)
# remote_theme: sproogen/modern-resume-theme (Use this if you are hosting your resume on GitHub)

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag

exclude : [
  "Gemfile",
  "Gemfile.lock",
  "node_modules",
  "vendor/bundle/",
  "vendor/cache/",
  "vendor/gems/",
  "vendor/ruby/",
  "lib/",
  "scripts/",
  "docker-compose.yml",
  ]
  
  
  
  
  
